// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  originX: __t.f32(),
  originZ: __t.f32(),
  dirX: __t.f32(),
  dirZ: __t.f32(),
  range: __t.f32(),
  hitRadius: __t.f32(),
  isSkill: __t.bool(),
  comboCount: __t.u32(),
};
