// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitKind: __t.u32().name("unit_kind"),
  unitId: __t.u64().name("unit_id"),
  attackId: __t.string().name("attack_id"),
  landingX: __t.f32().name("landing_x"),
  landingZ: __t.f32().name("landing_z"),
  radius: __t.f32(),
});
