// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  bannerId: __t.string().name("banner_id"),
  pullsSinceFiveStar: __t.u32().name("pulls_since_five_star"),
  pullsSinceFourStar: __t.u32().name("pulls_since_four_star"),
  guaranteedFeatured: __t.bool().name("guaranteed_featured"),
  totalPulls: __t.u32().name("total_pulls"),
});
