// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  enemyId: __t.u64().primaryKey().name("enemy_id"),
  campIndex: __t.u32().name("camp_index"),
  archetypeId: __t.string().name("archetype_id"),
  isBoss: __t.bool().name("is_boss"),
  rewardTier: __t.u32().name("reward_tier"),
  homeX: __t.f32().name("home_x"),
  homeZ: __t.f32().name("home_z"),
  positionX: __t.f32().name("position_x"),
  positionZ: __t.f32().name("position_z"),
  health: __t.u32(),
  maxHealth: __t.u32().name("max_health"),
  contactDamage: __t.u32().name("contact_damage"),
  carriedGems: __t.u32().name("carried_gems"),
  aggroKind: __t.u32().name("aggro_kind"),
  aggroPlayer: __t.option(__t.identity()).name("aggro_player"),
  aggroGoliathId: __t.u64().name("aggro_goliath_id"),
  aggroExpiresAtMicros: __t.u64().name("aggro_expires_at_micros"),
  alive: __t.bool(),
  respawnAtMicros: __t.u64().name("respawn_at_micros"),
});
