// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  enemyId: __t.u64().primaryKey().name("enemy_id"),
  carriedGems: __t.u32().name("carried_gems"),
  lastGrabbedBy: __t.identity().name("last_grabbed_by"),
  killedAtMicros: __t.u64().name("killed_at_micros"),
});
