// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  goliathId: __t.u64().primaryKey().name("goliath_id"),
  sizeIndex: __t.u32().name("size_index"),
  positionX: __t.f32().name("position_x"),
  positionZ: __t.f32().name("position_z"),
  health: __t.u32(),
  maxHealth: __t.u32().name("max_health"),
  contactDamage: __t.u32().name("contact_damage"),
  moveSpeed: __t.f32().name("move_speed"),
  splashes: __t.bool(),
  carriedGems: __t.u32().name("carried_gems"),
  targetCampIndex: __t.i32().name("target_camp_index"),
  aggroPlayer: __t.option(__t.identity()).name("aggro_player"),
  aggroExpiresAtMicros: __t.u64().name("aggro_expires_at_micros"),
  alive: __t.bool(),
  windowBucket: __t.u64().name("window_bucket"),
  engageEndsAtMicros: __t.u64().name("engage_ends_at_micros"),
  lastRaidedCampIndex: __t.i32().name("last_raided_camp_index"),
  headingX: __t.f32().name("heading_x"),
  headingZ: __t.f32().name("heading_z"),
});
