// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "./accept_invite_reducer";
import AttackEnemiesReducer from "./attack_enemies_reducer";
import AttackPlayerReducer from "./attack_player_reducer";
import AttackRayReducer from "./attack_ray_reducer";
import CastSkillReducer from "./cast_skill_reducer";
import CollectGemReducer from "./collect_gem_reducer";
import CollectShardReducer from "./collect_shard_reducer";
import DeclineInviteReducer from "./decline_invite_reducer";
import FallToDeathReducer from "./fall_to_death_reducer";
import HealInSafeZoneReducer from "./heal_in_safe_zone_reducer";
import HealPartyReducer from "./heal_party_reducer";
import InvitePlayerReducer from "./invite_player_reducer";
import LeavePartyReducer from "./leave_party_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import PingReducer from "./ping_reducer";
import PullBannerReducer from "./pull_banner_reducer";
import RegisterReducer from "./register_reducer";
import RequestJoinReducer from "./request_join_reducer";
import RestoreBannerPityReducer from "./restore_banner_pity_reducer";
import RestoreOwnedCharactersReducer from "./restore_owned_characters_reducer";
import RestorePlayersReducer from "./restore_players_reducer";
import RestoreWeaponItemsReducer from "./restore_weapon_items_reducer";
import SeedWorldReducer from "./seed_world_reducer";
import SetActiveCharacterReducer from "./set_active_character_reducer";
import SetConstellationReducer from "./set_constellation_reducer";
import SetPartyReducer from "./set_party_reducer";
import TakeDamageReducer from "./take_damage_reducer";
import TranscendCharacterReducer from "./transcend_character_reducer";
import UpdatePositionReducer from "./update_position_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountLinkRow from "./account_link_table";
import BannerPityRow from "./banner_pity_table";
import CharacterActivationRow from "./character_activation_table";
import EnemyRow from "./enemy_table";
import GemDropRow from "./gem_drop_table";
import GoliathRow from "./goliath_table";
import HealEventRow from "./heal_event_table";
import OwnedCharacterRow from "./owned_character_table";
import PartyRow from "./party_table";
import PartyInviteRow from "./party_invite_table";
import PartyMemberRow from "./party_member_table";
import PlayerRow from "./player_table";
import PullResultRow from "./pull_result_table";
import PvpHitRow from "./pvp_hit_table";
import RangedAttackRow from "./ranged_attack_table";
import ShardDropRow from "./shard_drop_table";
import SkillCastRow from "./skill_cast_table";
import WeaponItemRow from "./weapon_item_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accountLink: __table({
    name: 'account_link',
    indexes: [
      { accessor: 'identity', name: 'account_link_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'account_link_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountLinkRow),
  bannerPity: __table({
    name: 'banner_pity',
    indexes: [
      { accessor: 'id', name: 'banner_pity_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_owner_banner', name: 'banner_pity_owner_banner_id_idx_btree', algorithm: 'btree', columns: [
        'owner',
        'bannerId',
      ] },
    ],
    constraints: [
      { name: 'banner_pity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BannerPityRow),
  characterActivation: __table({
    name: 'character_activation',
    indexes: [
      { accessor: 'id', name: 'character_activation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_owner_character', name: 'character_activation_owner_character_id_idx_btree', algorithm: 'btree', columns: [
        'owner',
        'characterId',
      ] },
      { accessor: 'owner', name: 'character_activation_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'character_activation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterActivationRow),
  enemy: __table({
    name: 'enemy',
    indexes: [
      { accessor: 'enemyId', name: 'enemy_enemy_id_idx_btree', algorithm: 'btree', columns: [
        'enemyId',
      ] },
    ],
    constraints: [
      { name: 'enemy_enemy_id_key', constraint: 'unique', columns: ['enemyId'] },
    ],
  }, EnemyRow),
  gemDrop: __table({
    name: 'gem_drop',
    indexes: [
      { accessor: 'id', name: 'gem_drop_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gem_drop_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GemDropRow),
  goliath: __table({
    name: 'goliath',
    indexes: [
      { accessor: 'goliathId', name: 'goliath_goliath_id_idx_btree', algorithm: 'btree', columns: [
        'goliathId',
      ] },
    ],
    constraints: [
      { name: 'goliath_goliath_id_key', constraint: 'unique', columns: ['goliathId'] },
    ],
  }, GoliathRow),
  healEvent: __table({
    name: 'heal_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, HealEventRow),
  ownedCharacter: __table({
    name: 'owned_character',
    indexes: [
      { accessor: 'id', name: 'owned_character_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'owned_character_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'owned_character_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OwnedCharacterRow),
  party: __table({
    name: 'party',
    indexes: [
      { accessor: 'id', name: 'party_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyRow),
  partyInvite: __table({
    name: 'party_invite',
    indexes: [
      { accessor: 'id', name: 'party_invite_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'joinerIdentity', name: 'party_invite_joiner_identity_idx_btree', algorithm: 'btree', columns: [
        'joinerIdentity',
      ] },
      { accessor: 'partyId', name: 'party_invite_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { accessor: 'recipientIdentity', name: 'party_invite_recipient_identity_idx_btree', algorithm: 'btree', columns: [
        'recipientIdentity',
      ] },
    ],
    constraints: [
      { name: 'party_invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyInviteRow),
  partyMember: __table({
    name: 'party_member',
    indexes: [
      { accessor: 'id', name: 'party_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'party_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'partyId', name: 'party_member_party_id_idx_btree', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_member_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'party_member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PartyMemberRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  pullResult: __table({
    name: 'pull_result',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, PullResultRow),
  pvpHit: __table({
    name: 'pvp_hit',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, PvpHitRow),
  rangedAttack: __table({
    name: 'ranged_attack',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, RangedAttackRow),
  shardDrop: __table({
    name: 'shard_drop',
    indexes: [
      { accessor: 'id', name: 'shard_drop_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'shard_drop_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ShardDropRow),
  skillCast: __table({
    name: 'skill_cast',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, SkillCastRow),
  weaponItem: __table({
    name: 'weapon_item',
    indexes: [
      { accessor: 'id', name: 'weapon_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'weapon_item_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'weapon_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WeaponItemRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_invite", AcceptInviteReducer),
  __reducerSchema("attack_enemies", AttackEnemiesReducer),
  __reducerSchema("attack_player", AttackPlayerReducer),
  __reducerSchema("attack_ray", AttackRayReducer),
  __reducerSchema("cast_skill", CastSkillReducer),
  __reducerSchema("collect_gem", CollectGemReducer),
  __reducerSchema("collect_shard", CollectShardReducer),
  __reducerSchema("decline_invite", DeclineInviteReducer),
  __reducerSchema("fall_to_death", FallToDeathReducer),
  __reducerSchema("heal_in_safe_zone", HealInSafeZoneReducer),
  __reducerSchema("heal_party", HealPartyReducer),
  __reducerSchema("invite_player", InvitePlayerReducer),
  __reducerSchema("leave_party", LeavePartyReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("ping", PingReducer),
  __reducerSchema("pull_banner", PullBannerReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("request_join", RequestJoinReducer),
  __reducerSchema("restore_banner_pity", RestoreBannerPityReducer),
  __reducerSchema("restore_owned_characters", RestoreOwnedCharactersReducer),
  __reducerSchema("restore_players", RestorePlayersReducer),
  __reducerSchema("restore_weapon_items", RestoreWeaponItemsReducer),
  __reducerSchema("seed_world", SeedWorldReducer),
  __reducerSchema("set_active_character", SetActiveCharacterReducer),
  __reducerSchema("set_constellation", SetConstellationReducer),
  __reducerSchema("set_party", SetPartyReducer),
  __reducerSchema("take_damage", TakeDamageReducer),
  __reducerSchema("transcend_character", TranscendCharacterReducer),
  __reducerSchema("update_position", UpdatePositionReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

