// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  partyId: __t.u64().name("party_id"),
  joinerIdentity: __t.identity().name("joiner_identity"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  kind: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
