// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  online: __t.bool(),
  positionX: __t.f32().name("position_x"),
  positionY: __t.f32().name("position_y"),
  positionZ: __t.f32().name("position_z"),
  rotationY: __t.f32().name("rotation_y"),
  activeCharacterId: __t.string().name("active_character_id"),
  primogems: __t.u32(),
  currentHealth: __t.u32().name("current_health"),
});
