// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  online: __t.bool(),
  positionX: __t.f32().name("position_x"),
  positionY: __t.f32().name("position_y"),
  positionZ: __t.f32().name("position_z"),
  rotationY: __t.f32().name("rotation_y"),
  activeCharacterId: __t.string().name("active_character_id"),
  partyOrder: __t.array(__t.string()).name("party_order"),
  gems: __t.u32(),
  currentHealth: __t.u32().name("current_health"),
  lastKillRewardAt: __t.timestamp().name("last_kill_reward_at"),
  gemsFromKills: __t.u32().name("gems_from_kills"),
  gemsCollected: __t.u32().name("gems_collected"),
  transcendShards: __t.u32().name("transcend_shards"),
  skillReadyAtMicros: __t.u64().name("skill_ready_at_micros"),
  skillWindowEndsAtMicros: __t.u64().name("skill_window_ends_at_micros"),
});
