// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  attacker: __t.identity(),
  characterId: __t.string().name("character_id"),
  originX: __t.f32().name("origin_x"),
  originZ: __t.f32().name("origin_z"),
  directionX: __t.f32().name("direction_x"),
  directionZ: __t.f32().name("direction_z"),
});
