// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  accountId: __t.u64(),
  username: __t.string(),
  usernameLower: __t.string(),
  email: __t.string(),
  passwordHash: __t.string(),
  salt: __t.string(),
  canonicalIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AccountLink = __t.object("AccountLink", {
  identity: __t.identity(),
  accountId: __t.u64(),
  canonicalIdentity: __t.identity(),
  username: __t.string(),
});
export type AccountLink = __Infer<typeof AccountLink>;

export const BannerPity = __t.object("BannerPity", {
  id: __t.u64(),
  owner: __t.identity(),
  bannerId: __t.string(),
  pullsSinceFiveStar: __t.u32(),
  pullsSinceFourStar: __t.u32(),
  guaranteedFeatured: __t.bool(),
  totalPulls: __t.u32(),
});
export type BannerPity = __Infer<typeof BannerPity>;

export const CharacterActivation = __t.object("CharacterActivation", {
  id: __t.u64(),
  owner: __t.identity(),
  characterId: __t.string(),
  activatedConstellation: __t.u32(),
});
export type CharacterActivation = __Infer<typeof CharacterActivation>;

export const Enemy = __t.object("Enemy", {
  enemyId: __t.u64(),
  campIndex: __t.u32(),
  archetypeId: __t.string(),
  isBoss: __t.bool(),
  rewardTier: __t.u32(),
  homeX: __t.f32(),
  homeZ: __t.f32(),
  positionX: __t.f32(),
  positionZ: __t.f32(),
  health: __t.u32(),
  maxHealth: __t.u32(),
  contactDamage: __t.u32(),
  carriedGems: __t.u32(),
  aggroKind: __t.u32(),
  aggroPlayer: __t.option(__t.identity()),
  aggroGoliathId: __t.u64(),
  aggroExpiresAtMicros: __t.u64(),
  alive: __t.bool(),
  respawnAtMicros: __t.u64(),
});
export type Enemy = __Infer<typeof Enemy>;

export const GemDrop = __t.object("GemDrop", {
  id: __t.u64(),
  positionX: __t.f32(),
  positionZ: __t.f32(),
  amount: __t.u32(),
  droppedBy: __t.identity(),
  droppedAtMicros: __t.u64(),
});
export type GemDrop = __Infer<typeof GemDrop>;

export const Goliath = __t.object("Goliath", {
  goliathId: __t.u64(),
  sizeIndex: __t.u32(),
  positionX: __t.f32(),
  positionZ: __t.f32(),
  health: __t.u32(),
  maxHealth: __t.u32(),
  contactDamage: __t.u32(),
  moveSpeed: __t.f32(),
  splashes: __t.bool(),
  carriedGems: __t.u32(),
  targetCampIndex: __t.i32(),
  aggroPlayer: __t.option(__t.identity()),
  aggroExpiresAtMicros: __t.u64(),
  alive: __t.bool(),
  windowBucket: __t.u64(),
  engageEndsAtMicros: __t.u64(),
  lastRaidedCampIndex: __t.i32(),
  headingX: __t.f32(),
  headingZ: __t.f32(),
});
export type Goliath = __Infer<typeof Goliath>;

export const HealEvent = __t.object("HealEvent", {
  owner: __t.identity(),
  characterId: __t.string(),
  amount: __t.u32(),
});
export type HealEvent = __Infer<typeof HealEvent>;

export const OwnedCharacter = __t.object("OwnedCharacter", {
  id: __t.u64(),
  owner: __t.identity(),
  characterId: __t.string(),
  currentHealth: __t.u32(),
  constellation: __t.u32(),
  transcendLevel: __t.u32(),
});
export type OwnedCharacter = __Infer<typeof OwnedCharacter>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  leaderIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const PartyInvite = __t.object("PartyInvite", {
  id: __t.u64(),
  partyId: __t.u64(),
  joinerIdentity: __t.identity(),
  recipientIdentity: __t.identity(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type PartyInvite = __Infer<typeof PartyInvite>;

export const PartyMember = __t.object("PartyMember", {
  id: __t.u64(),
  partyId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type PartyMember = __Infer<typeof PartyMember>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  positionZ: __t.f32(),
  rotationY: __t.f32(),
  activeCharacterId: __t.string(),
  partyOrder: __t.array(__t.string()),
  gems: __t.u32(),
  currentHealth: __t.u32(),
  lastKillRewardAt: __t.timestamp(),
  gemsFromKills: __t.u32(),
  gemsCollected: __t.u32(),
  transcendShards: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PullResult = __t.object("PullResult", {
  owner: __t.identity(),
  bannerId: __t.string(),
  slot: __t.u32(),
  kind: __t.string(),
  itemId: __t.string(),
  rarity: __t.u32(),
  isNew: __t.bool(),
  isFeatured: __t.bool(),
  constellation: __t.u32(),
  shardMinted: __t.u32(),
});
export type PullResult = __Infer<typeof PullResult>;

export const Puppet = __t.object("Puppet", {
  identity: __t.identity(),
});
export type Puppet = __Infer<typeof Puppet>;

export const PvpHit = __t.object("PvpHit", {
  target: __t.identity(),
  amount: __t.u32(),
});
export type PvpHit = __Infer<typeof PvpHit>;

export const RangedAttack = __t.object("RangedAttack", {
  attacker: __t.identity(),
  characterId: __t.string(),
  originX: __t.f32(),
  originZ: __t.f32(),
  directionX: __t.f32(),
  directionZ: __t.f32(),
});
export type RangedAttack = __Infer<typeof RangedAttack>;

export const RegenTimer = __t.object("RegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RegenTimer = __Infer<typeof RegenTimer>;

export const RestoreBannerPityRow = __t.object("RestoreBannerPityRow", {
  owner: __t.identity(),
  bannerId: __t.string(),
  pullsSinceFiveStar: __t.u32(),
  pullsSinceFourStar: __t.u32(),
  guaranteedFeatured: __t.bool(),
  totalPulls: __t.u32(),
});
export type RestoreBannerPityRow = __Infer<typeof RestoreBannerPityRow>;

export const RestoreOwnedCharacterRow = __t.object("RestoreOwnedCharacterRow", {
  owner: __t.identity(),
  characterId: __t.string(),
  currentHealth: __t.u32(),
  constellation: __t.u32(),
});
export type RestoreOwnedCharacterRow = __Infer<typeof RestoreOwnedCharacterRow>;

export const RestorePlayerRow = __t.object("RestorePlayerRow", {
  identity: __t.identity(),
  name: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  positionZ: __t.f32(),
  rotationY: __t.f32(),
  activeCharacterId: __t.string(),
  partyOrder: __t.array(__t.string()),
  gems: __t.u32(),
  currentHealth: __t.u32(),
  gemsFromKills: __t.u32(),
  gemsCollected: __t.u32(),
  transcendShards: __t.u32(),
});
export type RestorePlayerRow = __Infer<typeof RestorePlayerRow>;

export const RestoreWeaponItemRow = __t.object("RestoreWeaponItemRow", {
  owner: __t.identity(),
  weaponId: __t.string(),
  rarity: __t.u32(),
});
export type RestoreWeaponItemRow = __Infer<typeof RestoreWeaponItemRow>;

export const ShardDrop = __t.object("ShardDrop", {
  id: __t.u64(),
  positionX: __t.f32(),
  positionZ: __t.f32(),
  amount: __t.u32(),
  droppedBy: __t.identity(),
  droppedAtMicros: __t.u64(),
});
export type ShardDrop = __Infer<typeof ShardDrop>;

export const SkillCast = __t.object("SkillCast", {
  caster: __t.identity(),
  characterId: __t.string(),
  skillId: __t.string(),
  originX: __t.f32(),
  originZ: __t.f32(),
  directionX: __t.f32(),
  directionZ: __t.f32(),
});
export type SkillCast = __Infer<typeof SkillCast>;

export const WeaponItem = __t.object("WeaponItem", {
  id: __t.u64(),
  owner: __t.identity(),
  weaponId: __t.string(),
  rarity: __t.u32(),
  acquiredAt: __t.timestamp(),
});
export type WeaponItem = __Infer<typeof WeaponItem>;

export const WorldTimer = __t.object("WorldTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldTimer = __Infer<typeof WorldTimer>;

