// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BannerPity = __t.object("BannerPity", {
  id: __t.u64(),
  owner: __t.identity(),
  bannerId: __t.string(),
  pullsSinceFiveStar: __t.u32(),
  pullsSinceFourStar: __t.u32(),
  guaranteedFeatured: __t.bool(),
  totalPulls: __t.u32(),
});
export type BannerPity = __Infer<typeof BannerPity>;

export const OwnedCharacter = __t.object("OwnedCharacter", {
  id: __t.u64(),
  owner: __t.identity(),
  characterId: __t.string(),
  currentHealth: __t.u32(),
});
export type OwnedCharacter = __Infer<typeof OwnedCharacter>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  positionZ: __t.f32(),
  rotationY: __t.f32(),
  activeCharacterId: __t.string(),
  primogems: __t.u32(),
  currentHealth: __t.u32(),
  lastKillRewardAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PullResult = __t.object("PullResult", {
  owner: __t.identity(),
  bannerId: __t.string(),
  slot: __t.u32(),
  kind: __t.string(),
  itemId: __t.string(),
  rarity: __t.u32(),
  isNew: __t.bool(),
  isFeatured: __t.bool(),
});
export type PullResult = __Infer<typeof PullResult>;

export const RegenTimer = __t.object("RegenTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RegenTimer = __Infer<typeof RegenTimer>;

export const SkillCast = __t.object("SkillCast", {
  caster: __t.identity(),
  characterId: __t.string(),
  skillId: __t.string(),
  originX: __t.f32(),
  originZ: __t.f32(),
  directionX: __t.f32(),
  directionZ: __t.f32(),
});
export type SkillCast = __Infer<typeof SkillCast>;

export const WeaponItem = __t.object("WeaponItem", {
  id: __t.u64(),
  owner: __t.identity(),
  weaponId: __t.string(),
  rarity: __t.u32(),
  acquiredAt: __t.timestamp(),
});
export type WeaponItem = __Infer<typeof WeaponItem>;

