// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  unitKind: __t.u32().name("unit_kind"),
  unitId: __t.u64().name("unit_id"),
  state: __t.u32(),
  attackId: __t.string().name("attack_id"),
  startedAtMicros: __t.u64().name("started_at_micros"),
  strikeAtMicros: __t.u64().name("strike_at_micros"),
  recoveryEndsAtMicros: __t.u64().name("recovery_ends_at_micros"),
  cooldownUntilMicros: __t.u64().name("cooldown_until_micros"),
  landingX: __t.f32().name("landing_x"),
  landingZ: __t.f32().name("landing_z"),
  radius: __t.f32(),
  castX: __t.f32().name("cast_x"),
  castZ: __t.f32().name("cast_z"),
  strikeResolved: __t.bool().name("strike_resolved"),
  poise: __t.u32(),
});
