// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttackPlayerReducer from "../attack_player_reducer";
import CastSkillReducer from "../cast_skill_reducer";
import CollectGemReducer from "../collect_gem_reducer";
import DropGemsReducer from "../drop_gems_reducer";
import EnemyTakeGemReducer from "../enemy_take_gem_reducer";
import FallToDeathReducer from "../fall_to_death_reducer";
import HealInSafeZoneReducer from "../heal_in_safe_zone_reducer";
import HealPartyReducer from "../heal_party_reducer";
import JoinGameReducer from "../join_game_reducer";
import PullBannerReducer from "../pull_banner_reducer";
import SetActiveCharacterReducer from "../set_active_character_reducer";
import SetPartyReducer from "../set_party_reducer";
import TakeDamageReducer from "../take_damage_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type AttackPlayerParams = __Infer<typeof AttackPlayerReducer>;
export type CastSkillParams = __Infer<typeof CastSkillReducer>;
export type CollectGemParams = __Infer<typeof CollectGemReducer>;
export type DropGemsParams = __Infer<typeof DropGemsReducer>;
export type EnemyTakeGemParams = __Infer<typeof EnemyTakeGemReducer>;
export type FallToDeathParams = __Infer<typeof FallToDeathReducer>;
export type HealInSafeZoneParams = __Infer<typeof HealInSafeZoneReducer>;
export type HealPartyParams = __Infer<typeof HealPartyReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type PullBannerParams = __Infer<typeof PullBannerReducer>;
export type SetActiveCharacterParams = __Infer<typeof SetActiveCharacterReducer>;
export type SetPartyParams = __Infer<typeof SetPartyReducer>;
export type TakeDamageParams = __Infer<typeof TakeDamageReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

