// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "../accept_invite_reducer";
import AttackEnemiesReducer from "../attack_enemies_reducer";
import AttackPlayerReducer from "../attack_player_reducer";
import AttackRayReducer from "../attack_ray_reducer";
import CastSkillReducer from "../cast_skill_reducer";
import CollectGemReducer from "../collect_gem_reducer";
import CollectShardReducer from "../collect_shard_reducer";
import DeclineInviteReducer from "../decline_invite_reducer";
import FallToDeathReducer from "../fall_to_death_reducer";
import HealInSafeZoneReducer from "../heal_in_safe_zone_reducer";
import HealPartyReducer from "../heal_party_reducer";
import InvitePlayerReducer from "../invite_player_reducer";
import KickMemberReducer from "../kick_member_reducer";
import LeavePartyReducer from "../leave_party_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import PingReducer from "../ping_reducer";
import PullBannerReducer from "../pull_banner_reducer";
import RegisterReducer from "../register_reducer";
import RequestJoinReducer from "../request_join_reducer";
import RestoreBannerPityReducer from "../restore_banner_pity_reducer";
import RestoreOwnedCharactersReducer from "../restore_owned_characters_reducer";
import RestorePlayersReducer from "../restore_players_reducer";
import RestoreWeaponItemsReducer from "../restore_weapon_items_reducer";
import SeedWorldReducer from "../seed_world_reducer";
import SetActiveCharacterReducer from "../set_active_character_reducer";
import SetConstellationReducer from "../set_constellation_reducer";
import SetPartyReducer from "../set_party_reducer";
import TakeDamageReducer from "../take_damage_reducer";
import TranscendCharacterReducer from "../transcend_character_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type AcceptInviteParams = __Infer<typeof AcceptInviteReducer>;
export type AttackEnemiesParams = __Infer<typeof AttackEnemiesReducer>;
export type AttackPlayerParams = __Infer<typeof AttackPlayerReducer>;
export type AttackRayParams = __Infer<typeof AttackRayReducer>;
export type CastSkillParams = __Infer<typeof CastSkillReducer>;
export type CollectGemParams = __Infer<typeof CollectGemReducer>;
export type CollectShardParams = __Infer<typeof CollectShardReducer>;
export type DeclineInviteParams = __Infer<typeof DeclineInviteReducer>;
export type FallToDeathParams = __Infer<typeof FallToDeathReducer>;
export type HealInSafeZoneParams = __Infer<typeof HealInSafeZoneReducer>;
export type HealPartyParams = __Infer<typeof HealPartyReducer>;
export type InvitePlayerParams = __Infer<typeof InvitePlayerReducer>;
export type KickMemberParams = __Infer<typeof KickMemberReducer>;
export type LeavePartyParams = __Infer<typeof LeavePartyReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type PingParams = __Infer<typeof PingReducer>;
export type PullBannerParams = __Infer<typeof PullBannerReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RequestJoinParams = __Infer<typeof RequestJoinReducer>;
export type RestoreBannerPityParams = __Infer<typeof RestoreBannerPityReducer>;
export type RestoreOwnedCharactersParams = __Infer<typeof RestoreOwnedCharactersReducer>;
export type RestorePlayersParams = __Infer<typeof RestorePlayersReducer>;
export type RestoreWeaponItemsParams = __Infer<typeof RestoreWeaponItemsReducer>;
export type SeedWorldParams = __Infer<typeof SeedWorldReducer>;
export type SetActiveCharacterParams = __Infer<typeof SetActiveCharacterReducer>;
export type SetConstellationParams = __Infer<typeof SetConstellationReducer>;
export type SetPartyParams = __Infer<typeof SetPartyReducer>;
export type TakeDamageParams = __Infer<typeof TakeDamageReducer>;
export type TranscendCharacterParams = __Infer<typeof TranscendCharacterReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

