// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttackPlayerReducer from "../attack_player_reducer";
import CastSkillReducer from "../cast_skill_reducer";
import GrantKillRewardReducer from "../grant_kill_reward_reducer";
import HealInSafeZoneReducer from "../heal_in_safe_zone_reducer";
import JoinGameReducer from "../join_game_reducer";
import PullGachaReducer from "../pull_gacha_reducer";
import SetActiveCharacterReducer from "../set_active_character_reducer";
import TakeDamageReducer from "../take_damage_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type AttackPlayerParams = __Infer<typeof AttackPlayerReducer>;
export type CastSkillParams = __Infer<typeof CastSkillReducer>;
export type GrantKillRewardParams = __Infer<typeof GrantKillRewardReducer>;
export type HealInSafeZoneParams = __Infer<typeof HealInSafeZoneReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type PullGachaParams = __Infer<typeof PullGachaReducer>;
export type SetActiveCharacterParams = __Infer<typeof SetActiveCharacterReducer>;
export type TakeDamageParams = __Infer<typeof TakeDamageReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

